# Generated by Django 5.2 on 2025-05-08 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_made', models.BooleanField(default=False)),
                ('order_placed', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('order_reference', models.CharField(max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('paystack', 'Paystack')], help_text='The payment gateway used for this order.', max_length=50, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered_date', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
